// Package member holds the Member aggregate (UC-012..UC-017, UC-032).
// Pure domain — no GORM tags, no DB concerns.
package member

import (
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"

	memErrors "github.com/cuadra/cuadra-core/src/modules/members/domain/errors"
	phonepkg "github.com/cuadra/cuadra-core/src/shared/phone"
)

// Status mirrors chk_members_status.
const (
	StatusActive   = "active"
	StatusInactive = "inactive"
	StatusLost     = "lost"
)

// Gender values mirror chk_members_gender. Enum cerrado de 3 valores —
// captura siempre opcional. NULL en BD ≡ "no_especificado" para reportes
// (los socios pre-feature no se backfillean).
const (
	GenderMale        = "hombre"
	GenderFemale      = "mujer"
	GenderUnspecified = "no_especificado"
)

// Member-number identity (ADR-010). El número de socio es público, entero,
// único 1:1 por gym, y funciona como credencial de check-in cuando el
// biométrico no aplica. Reemplaza al antiguo "PIN de acceso" (superseded
// ADR-002): un solo concepto de identidad, no un secreto.
const (
	// DefaultMemberNumberDigits es la longitud inicial del número de socio.
	// Configurable por gym (sólo crece, monótono); ver gym.MemberNumberDigits.
	DefaultMemberNumberDigits = 4
	// MinMemberNumber es el piso del rango inicial [1000, 9999]: nunca se
	// generan números <1000. Backfills de PINs viejos pueden quedar por
	// debajo; el piso sólo aplica a la generación, no a la validación.
	MinMemberNumber = 1000
)

// Member is the gym client. Created via UC-012 with at least name + phone +
// gym_id. A Member has 0..1 active Membership at any time (enforced by the
// uq_memberships_member_active partial index). El número de socio es
// opcional; se asigna vía AssignMemberNumber (UC-032) o auto al crear.
type Member struct {
	ID                  uuid.UUID
	GymID               uuid.UUID
	Version             int
	Folio               string
	FullName            string
	Phone               string
	Email               *string
	Birthdate           *time.Time
	PhotoURL            *string
	Notes               *string
	Status              string
	EnrollmentPaid      bool
	LastMaintenancePaid *time.Time
	// MemberNumber es el identificador público del socio (ADR-010): entero,
	// único 1:1 por gym, también credencial de check-in. nil = sin número
	// asignado todavía (socio histórico o saturación del espacio). Es
	// público: se muestra en la credencial/banner y viaja por WhatsApp.
	// Reemplaza al par PinHash/PinPlain del modelo previo.
	MemberNumber         *int
	LastContactAttemptAt *time.Time
	// Gender es opcional y nullable. nil = el operador no capturó el campo
	// (socio histórico o "skip" deliberado). Si el operador elige
	// "Prefiero no decir" el use case persiste GenderUnspecified, no nil.
	// Sólo para reportes operativos del dueño — NO se expone en webhooks
	// salientes ni en CSV export default.
	Gender    *string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

// NewMember constructs a Member. Folio is generated by the use case (folio is
// gym-scoped). Birthdate / email / etc. are optional — pass nil for empty.
func NewMember(id, gymID uuid.UUID, folio, fullName, phone string, createdBy uuid.UUID, now time.Time) (*Member, error) {
	m := &Member{
		ID:        id,
		GymID:     gymID,
		Version:   1,
		Folio:     folio,
		Status:    StatusActive,
		CreatedBy: createdBy,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := m.applyFullName(fullName); err != nil {
		return nil, err
	}
	if err := m.applyPhone(phone); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileUpdate is UC-013's editable surface. nil = "no change".
type ProfileUpdate struct {
	FullName  *string
	Phone     *string
	Email     *string
	Birthdate *time.Time
	PhotoURL  *string
	Notes     *string
	// Gender — nil = no change. *Gender == "" limpia el campo (vuelve a NULL,
	// equivalente a "no se ha capturado"). Cualquier otro valor pasa por
	// ValidateGender; el caller responsable es UC-013 / UC-012.
	Gender *string
}

// ApplyProfileUpdate mutates fields that the operator is allowed to edit.
// Status, type of membership, and expiry_date live in their own use cases.
func (m *Member) ApplyProfileUpdate(u ProfileUpdate, now time.Time) error {
	changed := false
	if u.FullName != nil {
		if err := m.applyFullName(*u.FullName); err != nil {
			return err
		}
		changed = true
	}
	if u.Phone != nil {
		if err := m.applyPhone(*u.Phone); err != nil {
			return err
		}
		changed = true
	}
	if u.Email != nil {
		v := strings.TrimSpace(strings.ToLower(*u.Email))
		if v == "" {
			m.Email = nil
		} else {
			if !ValidateEmail(v) {
				return memErrors.ErrInvalidEmail
			}
			m.Email = &v
		}
		changed = true
	}
	if u.Birthdate != nil {
		t := *u.Birthdate
		if t.IsZero() {
			m.Birthdate = nil
		} else {
			if t.After(now) {
				return memErrors.ErrInvalidBirthdate
			}
			m.Birthdate = &t
		}
		changed = true
	}
	if u.PhotoURL != nil {
		v := strings.TrimSpace(*u.PhotoURL)
		if v == "" {
			m.PhotoURL = nil
		} else {
			m.PhotoURL = &v
		}
		changed = true
	}
	if u.Notes != nil {
		v := *u.Notes
		if len(v) > 2000 {
			return memErrors.ErrInvalidNotesTooLong
		}
		if strings.TrimSpace(v) == "" {
			m.Notes = nil
		} else {
			m.Notes = &v
		}
		changed = true
	}
	if u.Gender != nil {
		v := strings.TrimSpace(*u.Gender)
		if v == "" {
			m.Gender = nil
		} else {
			if err := ValidateGender(v); err != nil {
				return err
			}
			m.Gender = &v
		}
		changed = true
	}
	if changed {
		m.Version++
		m.UpdatedAt = now
	}
	return nil
}

// ChangeStatus toggles between active/inactive/lost (UC-016, UC-035). Reason
// is optional but kept by the caller in audit_log.
func (m *Member) ChangeStatus(newStatus string, now time.Time) error {
	switch newStatus {
	case StatusActive, StatusInactive, StatusLost:
	default:
		return memErrors.ErrInvalidStatus
	}
	if m.Status == newStatus {
		return nil
	}
	m.Status = newStatus
	m.Version++
	m.UpdatedAt = now
	return nil
}

// MarkEnrollmentPaid is called by billing when the enrollment_fee was charged
// (UC-018). Idempotent.
func (m *Member) MarkEnrollmentPaid(now time.Time) {
	if m.EnrollmentPaid {
		return
	}
	m.EnrollmentPaid = true
	m.Version++
	m.UpdatedAt = now
}

// UpdateLastMaintenance is called by billing when the maintenance_fee was
// charged (UC-018). Caller passes the payment date.
func (m *Member) UpdateLastMaintenance(paymentDate time.Time, now time.Time) {
	d := paymentDate
	m.LastMaintenancePaid = &d
	m.Version++
	m.UpdatedAt = now
}

// SetMemberNumber asigna el número de socio (ADR-010). El use case ya
// verificó la unicidad en el gym antes de llamar; el dominio sólo guarda
// el valor y bumpea version. El número es público — no se hashea (a
// diferencia del antiguo PIN).
func (m *Member) SetMemberNumber(number int, now time.Time) {
	n := number
	m.MemberNumber = &n
	m.Version++
	m.UpdatedAt = now
}

// RegisterContactAttempt updates last_contact_attempt_at (UC-035 — but the
// field exists from Sesión 2 because the schema has it).
func (m *Member) RegisterContactAttempt(now time.Time) {
	t := now
	m.LastContactAttemptAt = &t
	m.Version++
	m.UpdatedAt = now
}

func (m *Member) applyFullName(name string) error {
	v := strings.TrimSpace(name)
	if len(v) < 3 || len(v) > 100 {
		return memErrors.ErrInvalidName
	}
	m.FullName = v
	return nil
}

func (m *Member) applyPhone(phone string) error {
	// "" (input CRUDO vacío) es válido: socio SIN teléfono. La explicitud
	// vive en el borde (el FE exige el check "sin teléfono" y el use case
	// el flag NoPhone en el alta); el dominio sólo garantiza que si HAY
	// teléfono, sea canónico E.164. OJO: el check es sobre el input crudo
	// y NO sobre el normalizado — Normalize("abc") también deja "" y esa
	// basura debe seguir rebotando como ErrInvalidPhone, no colarse como
	// "sin teléfono".
	if strings.TrimSpace(phone) == "" {
		m.Phone = ""
		return nil
	}
	v := normalizePhone(phone)
	if !ValidatePhone(v) {
		return memErrors.ErrInvalidPhone
	}
	m.Phone = v
	return nil
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

var (
	emailRegex = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
	// Teléfono E.164-ish: '+' opcional + 10-15 dígitos. El '+' es opcional a
	// propósito (tolera leer data legacy sin código de país); en ESCRITURA
	// todo pasa antes por src/shared/phone.Normalize, que garantiza el '+' y el
	// código de país. La validación estricta vive en phone.Valid, en el borde
	// con Twilio (twilio.whatsappAddress).
	phoneCanonicalRegex = regexp.MustCompile(`^\+?[1-9]\d{9,14}$`)
)

// normalizePhone delega en el normalizador canónico (src/shared/phone): quita
// todo separador y antepone el código de país (MX) a los nacionales de 10
// dígitos, devolviendo E.164. Antes sólo quitaba separadores y dejaba pasar
// 10 dígitos pelados, que Twilio leía con un país equivocado.
func normalizePhone(raw string) string {
	return phonepkg.Normalize(raw)
}

// ValidatePhone accepts a normalized phone in E.164-ish form.
func ValidatePhone(phone string) bool {
	if phone == "" {
		return false
	}
	return phoneCanonicalRegex.MatchString(phone)
}

// ValidateEmail returns true when the address is structurally valid.
func ValidateEmail(email string) bool {
	if email == "" || len(email) > 254 {
		return false
	}
	return emailRegex.MatchString(email)
}

// ValidateFullName enforces 3..100.
func ValidateFullName(name string) error {
	v := strings.TrimSpace(name)
	if len(v) < 3 || len(v) > 100 {
		return memErrors.ErrInvalidName
	}
	return nil
}

// ValidateMemberNumber enforces "entero positivo". El rango inicial es
// [1000, 9999] pero crece con el bump de dígitos (ADR-010 §2.2), así que
// aquí sólo exigimos > 0 — el piso de generación (MinMemberNumber) vive en
// el asignador, no en la validación de un número entrante (que puede venir
// de un backfill de PIN viejo <1000).
func ValidateMemberNumber(n int) error {
	if n <= 0 {
		return memErrors.ErrInvalidMemberNumber
	}
	return nil
}

// ValidateGender acepta "" (significado: no se capturó) y los 3 valores del
// enum (hombre / mujer / no_especificado). Cualquier otra cosa devuelve
// ErrInvalidGender. El caller decide si "" debe persistirse como NULL o
// rechazarse — el dominio sólo valida el valor.
func ValidateGender(g string) error {
	switch g {
	case "", GenderMale, GenderFemale, GenderUnspecified:
		return nil
	default:
		return memErrors.ErrInvalidGender
	}
}

// SetGender — escritura directa del campo desde un punto distinto al
// ProfileUpdate (no se usa hoy en use cases pero queda disponible para
// futuras superficies como un endpoint dedicado). "" limpia el campo.
func (m *Member) SetGender(g string, now time.Time) error {
	v := strings.TrimSpace(g)
	if err := ValidateGender(v); err != nil {
		return err
	}
	if v == "" {
		if m.Gender == nil {
			return nil
		}
		m.Gender = nil
	} else {
		if m.Gender != nil && *m.Gender == v {
			return nil
		}
		m.Gender = &v
	}
	m.Version++
	m.UpdatedAt = now
	return nil
}

// ValidateStartDate enforces "hoy ± 30 días" (UC-012). today is the wall-clock
// date in the gym's timezone (caller computes that).
func ValidateStartDate(start, today time.Time) error {
	delta := start.Sub(today)
	if delta > 30*24*time.Hour || delta < -30*24*time.Hour {
		return memErrors.ErrInvalidStartDate
	}
	return nil
}

// Validator is the chain interface for create-time validation.
type Validator interface {
	Validate(m *Member) error
}

type nameValidator struct{ Next Validator }

func (v *nameValidator) Validate(m *Member) error {
	if err := ValidateFullName(m.FullName); err != nil {
		return err
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

type phoneValidator struct{ Next Validator }

func (v *phoneValidator) Validate(m *Member) error {
	// Sin teléfono ("") es un estado válido del socio; sólo se valida el
	// formato cuando hay valor.
	if m.Phone != "" && !ValidatePhone(m.Phone) {
		return memErrors.ErrInvalidPhone
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

type statusValidator struct{ Next Validator }

func (v *statusValidator) Validate(m *Member) error {
	switch m.Status {
	case StatusActive, StatusInactive, StatusLost:
	default:
		return memErrors.ErrInvalidStatus
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

func BuildValidatorChain() Validator {
	return &nameValidator{Next: &phoneValidator{Next: &statusValidator{}}}
}
