// Package member holds the Member aggregate (UC-012..UC-017, UC-032).
// Pure domain — no GORM tags, no DB concerns.
package member

import (
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"

	memErrors "github.com/cuadra/cuadra-core/src/modules/members/domain/errors"
)

// Status mirrors chk_members_status.
const (
	StatusActive   = "active"
	StatusInactive = "inactive"
	StatusLost     = "lost"
)

// Member is the gym client. Created via UC-012 with at least name + phone +
// gym_id. A Member has 0..1 active Membership at any time (enforced by the
// uq_memberships_member_active partial index). PIN is optional; assigned via
// AssignPin (UC-032).
type Member struct {
	ID                   uuid.UUID
	GymID                uuid.UUID
	Version              int
	Folio                string
	FullName             string
	Phone                string
	Email                *string
	Birthdate            *time.Time
	PhotoURL             *string
	Notes                *string
	Status               string
	EnrollmentPaid       bool
	LastMaintenancePaid  *time.Time
	PinHash              *string
	PinAssignedAt        *time.Time
	LastContactAttemptAt *time.Time
	CreatedBy            uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            *time.Time
}

// NewMember constructs a Member. Folio is generated by the use case (folio is
// gym-scoped). Birthdate / email / etc. are optional — pass nil for empty.
func NewMember(id, gymID uuid.UUID, folio, fullName, phone string, createdBy uuid.UUID, now time.Time) (*Member, error) {
	m := &Member{
		ID:        id,
		GymID:     gymID,
		Version:   1,
		Folio:     folio,
		Status:    StatusActive,
		CreatedBy: createdBy,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := m.applyFullName(fullName); err != nil {
		return nil, err
	}
	if err := m.applyPhone(phone); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileUpdate is UC-013's editable surface. nil = "no change".
type ProfileUpdate struct {
	FullName  *string
	Phone     *string
	Email     *string
	Birthdate *time.Time
	PhotoURL  *string
	Notes     *string
}

// ApplyProfileUpdate mutates fields that the operator is allowed to edit.
// Status, type of membership, and expiry_date live in their own use cases.
func (m *Member) ApplyProfileUpdate(u ProfileUpdate, now time.Time) error {
	changed := false
	if u.FullName != nil {
		if err := m.applyFullName(*u.FullName); err != nil {
			return err
		}
		changed = true
	}
	if u.Phone != nil {
		if err := m.applyPhone(*u.Phone); err != nil {
			return err
		}
		changed = true
	}
	if u.Email != nil {
		v := strings.TrimSpace(strings.ToLower(*u.Email))
		if v == "" {
			m.Email = nil
		} else {
			if !ValidateEmail(v) {
				return memErrors.ErrInvalidEmail
			}
			m.Email = &v
		}
		changed = true
	}
	if u.Birthdate != nil {
		t := *u.Birthdate
		if t.IsZero() {
			m.Birthdate = nil
		} else {
			if t.After(now) {
				return memErrors.ErrInvalidBirthdate
			}
			m.Birthdate = &t
		}
		changed = true
	}
	if u.PhotoURL != nil {
		v := strings.TrimSpace(*u.PhotoURL)
		if v == "" {
			m.PhotoURL = nil
		} else {
			m.PhotoURL = &v
		}
		changed = true
	}
	if u.Notes != nil {
		v := *u.Notes
		if len(v) > 2000 {
			return memErrors.ErrInvalidNotesTooLong
		}
		if strings.TrimSpace(v) == "" {
			m.Notes = nil
		} else {
			m.Notes = &v
		}
		changed = true
	}
	if changed {
		m.Version++
		m.UpdatedAt = now
	}
	return nil
}

// ChangeStatus toggles between active/inactive/lost (UC-016, UC-035). Reason
// is optional but kept by the caller in audit_log.
func (m *Member) ChangeStatus(newStatus string, now time.Time) error {
	switch newStatus {
	case StatusActive, StatusInactive, StatusLost:
	default:
		return memErrors.ErrInvalidStatus
	}
	if m.Status == newStatus {
		return nil
	}
	m.Status = newStatus
	m.Version++
	m.UpdatedAt = now
	return nil
}

// MarkEnrollmentPaid is called by billing when the enrollment_fee was charged
// (UC-018). Idempotent.
func (m *Member) MarkEnrollmentPaid(now time.Time) {
	if m.EnrollmentPaid {
		return
	}
	m.EnrollmentPaid = true
	m.Version++
	m.UpdatedAt = now
}

// UpdateLastMaintenance is called by billing when the maintenance_fee was
// charged (UC-018). Caller passes the payment date.
func (m *Member) UpdateLastMaintenance(paymentDate time.Time, now time.Time) {
	d := paymentDate
	m.LastMaintenancePaid = &d
	m.Version++
	m.UpdatedAt = now
}

// SetPin is called after the use case has hashed the PIN and verified
// gym-uniqueness. Domain doesn't hash; it just stores.
func (m *Member) SetPin(hash string, now time.Time) {
	h := hash
	m.PinHash = &h
	t := now
	m.PinAssignedAt = &t
	m.Version++
	m.UpdatedAt = now
}

// RegisterContactAttempt updates last_contact_attempt_at (UC-035 — but the
// field exists from Sesión 2 because the schema has it).
func (m *Member) RegisterContactAttempt(now time.Time) {
	t := now
	m.LastContactAttemptAt = &t
	m.Version++
	m.UpdatedAt = now
}

func (m *Member) applyFullName(name string) error {
	v := strings.TrimSpace(name)
	if len(v) < 3 || len(v) > 100 {
		return memErrors.ErrInvalidName
	}
	m.FullName = v
	return nil
}

func (m *Member) applyPhone(phone string) error {
	v := normalizePhone(phone)
	if !ValidatePhone(v) {
		return memErrors.ErrInvalidPhone
	}
	m.Phone = v
	return nil
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

var (
	emailRegex = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
	// Mexican mobile: 10 digits or +52 + 10 digits.
	phoneCanonicalRegex = regexp.MustCompile(`^\+?[1-9]\d{9,14}$`)
)

// normalizePhone strips spaces, dashes, parens. Returns the cleaned value.
func normalizePhone(raw string) string {
	v := strings.TrimSpace(raw)
	v = strings.ReplaceAll(v, " ", "")
	v = strings.ReplaceAll(v, "-", "")
	v = strings.ReplaceAll(v, "(", "")
	v = strings.ReplaceAll(v, ")", "")
	return v
}

// ValidatePhone accepts a normalized phone in E.164-ish form.
func ValidatePhone(phone string) bool {
	if phone == "" {
		return false
	}
	return phoneCanonicalRegex.MatchString(phone)
}

// ValidateEmail returns true when the address is structurally valid.
func ValidateEmail(email string) bool {
	if email == "" || len(email) > 254 {
		return false
	}
	return emailRegex.MatchString(email)
}

// ValidateFullName enforces 3..100.
func ValidateFullName(name string) error {
	v := strings.TrimSpace(name)
	if len(v) < 3 || len(v) > 100 {
		return memErrors.ErrInvalidName
	}
	return nil
}

// ValidatePin enforces "exactly 4 digits".
func ValidatePin(plain string) error {
	if len(plain) != 4 {
		return memErrors.ErrInvalidPin
	}
	for _, c := range plain {
		if c < '0' || c > '9' {
			return memErrors.ErrInvalidPin
		}
	}
	return nil
}

// ValidateStartDate enforces "hoy ± 30 días" (UC-012). today is the wall-clock
// date in the gym's timezone (caller computes that).
func ValidateStartDate(start, today time.Time) error {
	delta := start.Sub(today)
	if delta > 30*24*time.Hour || delta < -30*24*time.Hour {
		return memErrors.ErrInvalidStartDate
	}
	return nil
}

// Validator is the chain interface for create-time validation.
type Validator interface {
	Validate(m *Member) error
}

type nameValidator struct{ Next Validator }

func (v *nameValidator) Validate(m *Member) error {
	if err := ValidateFullName(m.FullName); err != nil {
		return err
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

type phoneValidator struct{ Next Validator }

func (v *phoneValidator) Validate(m *Member) error {
	if !ValidatePhone(m.Phone) {
		return memErrors.ErrInvalidPhone
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

type statusValidator struct{ Next Validator }

func (v *statusValidator) Validate(m *Member) error {
	switch m.Status {
	case StatusActive, StatusInactive, StatusLost:
	default:
		return memErrors.ErrInvalidStatus
	}
	if v.Next != nil {
		return v.Next.Validate(m)
	}
	return nil
}

func BuildValidatorChain() Validator {
	return &nameValidator{Next: &phoneValidator{Next: &statusValidator{}}}
}
